version: '3'

services:
  client-backend:

    image: diplom:2024
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8085"

  client:
          container_name: frontend-client
          build:
            context: netology-diplom-frontend
            dockerfile: Dockerfile
          image: front:latest

          ports:
                - "8080"











